# Generated by Django 4.0.4 on 2022-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('textid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('regDate', models.DateField()),
            ],
            options={
                'db_table': 'texts',
            },
        ),
    ]
